#planner_frequency: 0.5	
#planner_frequency: 0.25
planner_frequency: 0.0
controller_frequency: 10.0

DWAPlannerROS:
   max_trans_vel: 0.25
   min_trans_vel: 0.05
   #max_vel_x: 0.2	 
   max_vel_x: 0.25
   #min_vel_x: -0.1	
   min_vel_x: -0.05
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   #max_rot_vel: 1.0 
   max_rot_vel: 0.6
   min_rot_vel: 0.2
   acc_lim_x: 2.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   #acc_lim_theta: 3.2
   acc_lim_theta: 6.0

   yaw_goal_tolerance: 0.2 
   xy_goal_tolerance: 0.1  

   occdist_scale: 0.01

   oscillation_reset_dist: 0.05
   oscillation_reset_angle: 0.2

#   publish_cost_grid_pc: false
#   prune_plan: true
   path_distance_bias: 60
   sim_time: 2.0
   sim_granularity: 0.1
   angular_sim_granularity: 0.1
   vx_samples: 3
   vy_samples: 1  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   sum_scores: true
   publish_cost_grid_pc: true
   publish_traj_pc: true
#   simple_attractor: false

